artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/KarthikeyanBommannan/Telecommunication_Churning_MLOps/raw/main/telcoChurn.zip
  local_data_file: artifacts/data_ingestion/telcoChurn.zip
  unzip_dir: artifacts/data_ingestion
